# Fig4c - Bulk BST2 GSEA

library(tidyverse)
library(edgeR)
library(ggplot2)

setwd("~/Desktop/Dropbox/DBN2019/bulkBst2/gsea")

#==================================================================================================
# Read in EdgeR Output and Process
data <- read.table("../edger/data/glmLRT-Exp2-O.pos.over.O.neg.all.txt", header = T)
data$Z <- qnorm(1 - (data$PValue/2))
data$signedZ <- data$Z * sign(data$logFC)
data <- data[order(data$signedZ, decreasing=T),]
data$cZ <- qnorm(1 - (data$FDR/2)) * sign(data$logFC)

#==================================================================================================
# Make GSEA Broad Rank File
rank <- data[c("genes", "cZ")]
rank <- rank[abs(rank$VALUE) > 0, ]
rank$SYMBOL <- toupper(rank$SYMBOL)
colnames(rank) <- NULL
write.table(rank, file = "data/Bst2_broadGSEA.rnk", quote = F, row.names = FALSE, sep = "\t")

#==================================================================================================
# GSEA 
# The Broad javaGSEA GUI was used here, with parameters recorded as a command line:
# java -Xmx512m xtools.gsea.GseaPreranked –gmx gseaftp.broadinstitute.org://pub/gsea/gene_sets_final/h.all.v6.1.symbols.gmt -norm meandiv -nperm 1000 –rnk celltype.rnk -scoring_scheme classic -rpt_label celltype.output.file -create_svgs false -make_sets true -plot_top_x 20 -rnd_seed timestamp -set_max 500 -set_min 15 -zip_report false -out gsea.output.dir -gui false

#==================================================================================================
# Processing and plotting GSEA output
# Process .xls file generated by GSEA into a dataframe for plotting.
# CUSTOMIZE the following three paths:
GSEA_OUTPUT_PATH <- "GSEA_Output_05.02.18_classic.h.all.v6.1.symbols.BST2.GseaPreranked.1525281836259/"
UP_REG <- paste0(GSEA_OUTPUT_PATH, "gsea_report_for_na_pos_1525281836259.xls")
DOWN_REG <- paste0(GSEA_OUTPUT_PATH, "gsea_report_for_na_neg_1525281836259.xls")

up <- read.table(UP_REG, sep = c("\t"), header = T)
down <- read.table(DOWN_REG, sep = c("\t"), header = T)
up2 <- data.frame(Pway = up$NAME, ES = up$NES, FDR = up$FDR.q.val, Size = up$SIZE, UpDown = rep("Up", length(up$NAME)))
down2 <- data.frame(Pway = down$NAME, ES = down$NES, FDR = down$FDR.q.val, Size = down$SIZE, UpDown = rep("Down", length(down$NAME)))
both <- rbind(up2, down2)

# If FDR equals zero, that means that none of the permutations resulted in an outcome
# at least as significant as the empirical result for that group. 
# We can swap out zero for an upperbound: 1/{number of permutations}. We then use this both p-value and FDR. 
# The number of permutations used in this particular GSEA run was 1,000. So we use 0.001.
smallest_pval <- .001 # CUSTOMIZE based on permutation number of GSEA run.
neglogFDR <- vector()
color <- vector()
for (i in 1:length(both$Pway)) {
  if(both[i, "UpDown"] == "Up") {
  	neglogFDR_temp <- min((-log10(both[i, "FDR"])), -log10(smallest_pval))
   	neglogFDR <- c(neglogFDR, neglogFDR_temp)
   	color <- c(color, "#FF3333")
  } else {
    neglogFDR_temp <- max(log10(both[i, "FDR"]), log10(smallest_pval))
    neglogFDR <- c(neglogFDR, neglogFDR_temp)
    color <- c(color,"#00CCFF")
  }
}

# Clean up names.
names <- gsub("HALLMARK_", "", both$Pway)
names <- gsub("_", " ", names)

# Make plotting df
data1 <- data.frame(names = names, ES = both$ES,  neglogFDR = neglogFDR, color = color)
data1 <- data1[order(data1$ES, decreasing=FALSE), ] # Order pways levels by ES
data1$names <- as.character(data1$names)
data1$names <- factor(data1$names, levels=unique(data1$names), ordered = T)
data1$color <- as.character(data1$color)
data1$color <- factor(data1$color, levels=unique(data1$color), ordered = T)
data1 <- data1[abs(data1$neglogFDR) > -log10(0.01), ] # FDR cutoff
data1 <- data1[abs(data1$ES) > 1.8, ] # effect size cutoff

#==================================================================================================
# Barplot

p<-ggplot(data1)
p<-p+geom_bar(aes(x=data1$names,y=data1$ES,fill=data1$color),stat="identity")
p<-p+theme_classic() + ggtitle("Hallmark Signatures")
p<-p+coord_flip()+labs(x=NULL)
p<-p+theme(axis.text.x=element_text(size=15))
p<-p+theme(axis.title.x=element_text(size=22))
p<-p+theme(axis.text.y=element_text(size=15,face="bold"))
p<-p+theme(axis.text.x=element_text(angle=45,hjust=1))
p<-p+theme(axis.title.y=element_text(size=22))
p<-p+theme(plot.title=element_text(size=20))
p<-p+theme(axis.title.y=element_text(vjust=1))
p<-p+theme(axis.title.x=element_text(vjust=-0.10))
p<-p+scale_fill_manual(values=c("orange","firebrick"))
p<-p+theme(legend.position = "none") 
p<-p+theme(plot.margin=unit(c(1,1,1,1),"cm"))
ggsave("plots/Fig4c_gseaHallmarksBarplot_ES_fdrCutoff0.01.pdf", p, height = 8, width = 8)

